SELECT [UserId]
      ,[CreateDate]
      ,[ConfirmationToken]
      ,[IsConfirmed]
      ,[LastPasswordFailureDate]
      ,[PasswordFailuresSinceLastSuccess]
      ,[Password]
      ,[PasswordChangedDate]
      ,[PasswordSalt]
      ,[PasswordVerificationToken]
      ,[PasswordVerificationTokenExpirationDate]
  FROM [ITaoHuoEBuy].[dbo].[webpages_Membership]

  SELECT [UserId]
      ,[UserName]
  FROM [ITaoHuoEBuy].[dbo].[UserProfile]