//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBuy.App_GlobalResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 记住我? 的本地化字符串。
        /// </summary>
        public static string CheckRemember {
            get {
                return ResourceManager.GetString("CheckRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败。提供的用户名或密码不正确。 的本地化字符串。
        /// </summary>
        public static string ErrorLoginFailed {
            get {
                return ResourceManager.GetString("ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，且不多余 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string ErrorPasswordLength {
            get {
                return ResourceManager.GetString("ErrorPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码输入错误 的本地化字符串。
        /// </summary>
        public static string ErrorWrongValidateCode {
            get {
                return ResourceManager.GetString("ErrorWrongValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string StrConfirmPassWord {
            get {
                return ResourceManager.GetString("StrConfirmPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string StrPassWord {
            get {
                return ResourceManager.GetString("StrPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索商品 的本地化字符串。
        /// </summary>
        public static string StrSearchGoods {
            get {
                return ResourceManager.GetString("StrSearchGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string StrUserName {
            get {
                return ResourceManager.GetString("StrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string StrValidateCode {
            get {
                return ResourceManager.GetString("StrValidateCode", resourceCulture);
            }
        }
    }
}
