//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PageLanguage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换显示 的本地化字符串。
        /// </summary>
        internal static string BtnSwitchThumb {
            get {
                return ResourceManager.GetString("BtnSwitchThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string BtnUserPanel {
            get {
                return ResourceManager.GetString("BtnUserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看不清点我 的本地化字符串。
        /// </summary>
        internal static string BtnValiCodeNotClear {
            get {
                return ResourceManager.GetString("BtnValiCodeNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该页面需要登录或具有相关权限后才能访问！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNeedLogin {
            get {
                return ResourceManager.GetString("ErrorNeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新帐户 的本地化字符串。
        /// </summary>
        internal static string HintCreateAccount {
            get {
                return ResourceManager.GetString("HintCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入商品名 的本地化字符串。
        /// </summary>
        internal static string HintInputGoodsName {
            get {
                return ResourceManager.GetString("HintInputGoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (如果你没有帐户) 的本地化字符串。
        /// </summary>
        internal static string HintRegister {
            get {
                return ResourceManager.GetString("HintRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好， 的本地化字符串。
        /// </summary>
        internal static string HintWelcomeStr {
            get {
                return ResourceManager.GetString("HintWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热卖商品 的本地化字符串。
        /// </summary>
        internal static string StrBestSales {
            get {
                return ResourceManager.GetString("StrBestSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接到SNS账号 的本地化字符串。
        /// </summary>
        internal static string StrConnectSNS {
            get {
                return ResourceManager.GetString("StrConnectSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zeyuan Wu &amp; Fangzhou Long 的本地化字符串。
        /// </summary>
        internal static string StrCopyright {
            get {
                return ResourceManager.GetString("StrCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用本地帐户登录 的本地化字符串。
        /// </summary>
        internal static string StrLoginWithLocalAccounts {
            get {
                return ResourceManager.GetString("StrLoginWithLocalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台管理 的本地化字符串。
        /// </summary>
        internal static string TitleAdmin {
            get {
                return ResourceManager.GetString("TitleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        internal static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品目录 的本地化字符串。
        /// </summary>
        internal static string TitleGoodIndex {
            get {
                return ResourceManager.GetString("TitleGoodIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string TitleRegister {
            get {
                return ResourceManager.GetString("TitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱淘货电子购物网 的本地化字符串。
        /// </summary>
        internal static string TitleWebsite {
            get {
                return ResourceManager.GetString("TitleWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该服务暂时不可用 的本地化字符串。
        /// </summary>
        internal static string WarnServiceUnavailable {
            get {
                return ResourceManager.GetString("WarnServiceUnavailable", resourceCulture);
            }
        }
    }
}
