//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PageLanguage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换显示.
        /// </summary>
        internal static string BtnSwitchThumb {
            get {
                return ResourceManager.GetString("BtnSwitchThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        internal static string BtnUserPanel {
            get {
                return ResourceManager.GetString("BtnUserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看不清点我.
        /// </summary>
        internal static string BtnValiCodeNotClear {
            get {
                return ResourceManager.GetString("BtnValiCodeNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该页面需要登录或具有相关权限后才能访问！.
        /// </summary>
        internal static string ErrorNeedLogin {
            get {
                return ResourceManager.GetString("ErrorNeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新帐户.
        /// </summary>
        internal static string HintCreateAccount {
            get {
                return ResourceManager.GetString("HintCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入商品名.
        /// </summary>
        internal static string HintInputGoodsName {
            get {
                return ResourceManager.GetString("HintInputGoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (如果你没有帐户).
        /// </summary>
        internal static string HintRegister {
            get {
                return ResourceManager.GetString("HintRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好，.
        /// </summary>
        internal static string HintWelcomeStr {
            get {
                return ResourceManager.GetString("HintWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热卖商品.
        /// </summary>
        internal static string StrBestSales {
            get {
                return ResourceManager.GetString("StrBestSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接到SNS账号.
        /// </summary>
        internal static string StrConnectSNS {
            get {
                return ResourceManager.GetString("StrConnectSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeyuan Wu &amp; Fangzhou Long.
        /// </summary>
        internal static string StrCopyright {
            get {
                return ResourceManager.GetString("StrCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用本地帐户登录.
        /// </summary>
        internal static string StrLoginWithLocalAccounts {
            get {
                return ResourceManager.GetString("StrLoginWithLocalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台管理.
        /// </summary>
        internal static string TitleAdmin {
            get {
                return ResourceManager.GetString("TitleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物车.
        /// </summary>
        internal static string TitleCart {
            get {
                return ResourceManager.GetString("TitleCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式.
        /// </summary>
        internal static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品目录.
        /// </summary>
        internal static string TitleGoodIndex {
            get {
                return ResourceManager.GetString("TitleGoodIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string TitleRegister {
            get {
                return ResourceManager.GetString("TitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱淘货电子购物网.
        /// </summary>
        internal static string TitleWebsite {
            get {
                return ResourceManager.GetString("TitleWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该服务暂时不可用.
        /// </summary>
        internal static string WarnServiceUnavailable {
            get {
                return ResourceManager.GetString("WarnServiceUnavailable", resourceCulture);
            }
        }
    }
}
